version: '2'

services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      
    command: flask run --host=0.0.0.0 --port 8000

  postgres:
    ports:
      - "5432"
